name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # 设置你需要的 Ruby 版本
          bundler-cache: true
      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install
      - name: Install Python dependencies
        run: |
          python -m venv venv  # 创建虚拟环境
          source venv/bin/activate  # 激活虚拟环境
          pip install -r requirements.txt  # 安装 Python 包
      - name: Execute conversion script
        run: |
          source venv/bin/activate  # 激活虚拟环境
          python scripts/convert_notebooks.py  # 运行你的 Python 脚本
      - name: Build with Jekyll
        run: |
          bundle exec jekyll build  # 构建你的 Jekyll 站点
      - name: List _site directory
        run: ls -la _site
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: site
